
<style type="text/css">
    .bannerSection {
        position: relative;
        display: none !important;
    }
    .headerSection nav.navbar.navbar-default {
        border-bottom: solid 2px #a0a0a000 !important;
    }
    .content_terms
    {
      height: 650px;
      overflow-y: auto;
    }

    .img-fluid
    {
      width: 100%;
    }
</style>


<div class="row innerPagesWrapper">
    <div class="col-md-12 content_terms">
      <div class="row innerPageHead">
        <div class="col-sm-9">
              <h3 class="title">Terms of Use </h3>
        </div>
        <div class="col-sm-3 innerLogo"><img src="{{ asset('images/blackRed-Logo.png') }}" class="img-fluid"></div>
      </div>
      <p>Welcome to the elysiumnetwork.io website (the “Website”) of Elysium Capital Limited  or “us”, “we or Elysium”). You (the “User”) have requested access to the Website, the Services (deﬁned below) that we provide through the Website and information, images, graphics, data, text, ﬁles, links, photographs, graphics, audio, video, messages, software, messages, communications, content, organization, design, compilation, magnetic translation, digital conversion, HTML, XML, Java code and other content related to the Website (collectively “Content”). Please carefully read the terms and conditions of use of the Website and Content (these “Terms of Use”). Your access and use of the Website and Content is conditioned on your acceptance and agreement without modiﬁcation to these Terms of Use. By clicking the “I Do Not Accept” button, you will not be permitted access to the Website. Please note that other portions of the Website may contain additional and/or different terms and conditions of use.</p>
      <p>Access</p>
      <p>We may provide you with a variety of resources, such as news and information about Elysium, your account information, the ability to communicate electronically with Elysium, and access to services and information available from time to time on or through the Website (the “Services”). We reserve the right in our sole and absolute discretion to terminate, modify, or suspend your access to the Website, Content or Services at any time (for any reason, or for no reason). In particular, and without limitation, we may terminate, modify, or suspend your access to the Website, Content and/or Services upon your non-compliance with these Terms of Use, and, if you are an Afﬁliate of Elysium, your Application and Agreement (the “Elysium  Agreement”) or if you violate our rights or the rights of any other party.</p>
      <p>Privacy</p>
      <p>Our Privacy Policy is incorporated into, and made a part of, these Terms of Use.</p>
      <p>Conduct</p>
      <p>You represent and warrant that (a) you are at least 18 years of age, (b) your use of the Website and Content is legal in, and does not violate any laws or rules of, the jurisdictions in which you reside or from which you use or otherwise access the Website, (c) all information (if any) provided by you to us is correct, (d) you possess the legal right and ability to enter into these Terms of Use, (e) your use of the Website and Content shall be in accordance with these Terms of Use (and if you are an Afﬁliate of Elysium, the Elysium  Agreement and the Policies and Procedures), (f) your use of the Website and Content shall be in accordance with all applicable laws and regulations, (g) you are capable of assuming, and do assume, any risks related to the use of the Website and Content, and (h) you understand and accept the terms, conditions and risks relating to the use of the Website and Content.</p>
      <p>You may not copy, transmit, distribute, sell or publish any or all of the Website, Content or Services, without our prior, express and written consent. In your use of the Content, such as printing it, you may not remove or alter, or cause to be removed or altered, any notice, mark, or legend in or on the Content, including, but not limited to, copyright notices, trademarks, and disclaimers. You may not create derivative works of the Website or Content. In connection with your access to, and/or use of, the Website and Content, you agree not to:</p>
      <p>(i) Use the Website, Content or Services, in whole or in part, except as expressly provided in these Terms of Use or use the Website or Content for any purpose that is unlawful, immoral, or prohibited by these Terms of Use or any applicable local, state, or federal law, rule, or regulation;<br />
      (ii) Use the Website, Content or Services in any manner that could damage, disable, overburden, or impair the Website, Content or Services, or interfere with any other party’s use and enjoyment of the Website, Content or Services;<br />
      (iii) Obtain, or attempt to obtain, any materials, information, or other Content through any means not intentionally made available or provided for through the Website;<br />
      (iv) Circumvent, or attempt to circumvent, any security feature of the Website;<br />
      (v) Modify, delete, decompile, disassemble or reverse engineer the Website, Content or Services in any way whatsoever;<br />
      (vi) Upload, e-mail or otherwise transmit to or through the Website or Services, any advertising, promotional, or other unauthorized communication, including, without limitation, “junk mail,” “surveys,” unsolicited e-mail, “spam,” “chain letters,” or “pyramid schemes”;<br />
      (vii) Upload, post, email, or otherwise transmit any material that contains “trojan horses,” “worms,” software viruses, or any other computer code, ﬁles, or programs designed to or that might interrupt, destroy, interfere or limit the functionality of the Website, Content or Services, or any computer software or hardware or telecommunications equipment;<br />
      (viii) Use any automated means, including, but not limited to, electronic “spiders,” “robots,” or “crawlers,” to download data from any of our databases; or<br />
      (ix) Incorporate data from any of our databases into any emails or other “white pages” products or services, whether browser-based, based on proprietary client-side applications, or web-based, without our prior, express and written consent.</p>
      <p>Intellectual Property Rights</p>
      <p>Unless otherwise indicated, our Website and Content are property of Elysium, its afﬁliates, its licensors or other third parties and are protected under applicable copyright, trademark, patent, and other intellectual property rights and laws. Except as speciﬁcally allowed in these Terms of Use, the copying, redistribution, use, or publication by you of the Content is strictly prohibited. No ownership or other interest or license in or to any patent, copyright, trademark, trade secret and other intellectual property rights or to the Content are being granted, assigned or transferred in these Terms of Use or by reason of your access to, and use of, the Website, Content or Services.
      </p>
      <p>All trademarks, service marks, trade names and copyrights displayed on the Website or in the Content are proprietary to us or their respective owners. You acquire no rights or licenses in or to any trademarks, service marks, trade names or copyrights displayed on the Website.</p>
        <p>Access to the Website and Content, and use of our Services, are being provided for your business use only. You may not reproduce, republish, distribute, assign, sublicense, retransmit, sell, or prepare derivative works of the Website or Content, or resell or make our Services available to others. All rights in and to the Website and our Content not expressly granted in these Terms of Use remain in us or in our licensors.
        </p>
        <p>Conﬁdential and Proprietary Information </p>
        <p>During the course of your use of the Website, you may have access to information which is conﬁdential and proprietary to us or our suppliers, licensors, or other similar entities. The term “Proprietary Information” means any information or material which is proprietary and conﬁdential to us or our suppliers, licensors or other similar entities, and includes any of the following information and material licensed, owned or developed by any such party or its agents: business records and plans; business information; product formulation and speciﬁcations; marketing plans and strategies; ﬁnancial statements; Afﬁliate lists and information, genealogies, compensation plans and ﬁnancial information, customer lists and records; technical information; inventions; product design; information; services; pricing structure; discounts; computer programs and listings; source code and/or object code; software; and any other such proprietary information. You understand and acknowledge that the Proprietary Information is owned, obtained or licensed by us or our suppliers, licensors, or other similar entities, by the investment of signiﬁcant time, effort and expense, and that the Proprietary Information is a valuable, special and unique asset of ours or our suppliers, licensors, or other similar entities, which provides us with a signiﬁcant competitive advantage. Therefore, you must hold in conﬁdence and not disclose the Proprietary Information to any person or entity without our prior written consent. You shall be liable for any and all breaches of Terms of Use and any unauthorized use or disclosure of Proprietary Information. If you become compelled by applicable law, regulation or legal process to disclose any of the Proprietary Information, you shall promptly provide us with notice in order for us to seek a protective order or other appropriate remedy. Further, if you become compelled to disclose any of the Proprietary Information, you must disclose only that portion of the Proprietary Information you are legally required to disclose as conﬁrmed by a legal opinion of your counsel at your expense. Upon our request, you shall return all materials containing Proprietary Information.</p>
        <p>Indemniﬁcation </p>
        <p>You shall indemnify, defend, and hold us, our afﬁliates and our licensors, owners, ofﬁcers, directors, employees, subcontractors, information providers, suppliers, attorneys, agents, parents, subsidiaries and afﬁliated entities, and the owners, ofﬁcers, directors, employees, subcontractors, attorneys, agents, parents, subsidiaries and afﬁliated entities of each of them (collectively, “our Afﬁliated Parties”) harmless from any liability, loss, claim, damages, suit, judgment, cost or expense, including, but not limited to, reasonable attorneys’ fees, related to your (a) failure to comply with any of these Terms and Conditions or (b) use of the Website or Content. We have no duty to reimburse, defend, indemnify, or hold you harmless resulting from, relating to, or arising out of, these Terms and Conditions, the Website, or your access to or use of the Website or Content.
        </p>
        <p>Disclaimers</p>
        <p>WE MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE WEBSITE, THE SERVICES OR THE CONTENT CONTAINED ON THE WEBSITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE WEBSITE AND ALL SUCH CONTENT, SERVICES, SOFTWARE AND PRODUCTS ARE PROVIDED “AS IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE.” WE DISCLAIM ALL WARRANTIES, EXPRESS AND IMPLIED, ARISING OUT OF, OR IN CONNECTION WITH, THE WEBSITE, SERVICES AND CONTENT, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE AND THOSE ARISING BY LAW, STATUTE, USAGE OF TRADE OR COURSE OF DEALING AND ANY LIABILITY WITH REGARD TO THE WEBSITE, CONTENT AND SERVICES AND ANY ACTIONS RESULTING FROM YOUR PARTICIPATION IN ANY SERVICE. </p>
        <p>YOUR USE OF THE WEBSITE, SERVICES AND CONTENT IS AT YOUR SOLE RISK. ALTHOUGH OUR CONTENT MAY BE UPDATED FROM TIME TO TIME, IT MAY BE OUT OF DATE AND/OR MAY CONTAIN INACCURACIES OR TYPOGRAPHICAL ERRORS. WE ARE NOT RESPONSIBLE FOR YOUR INABILITY OR FAILURE (FOR ANY REASON) TO ACCESS THE WEBSITE OR CONTENT OR OTHERWISE USE OR RECEIVE INFORMATION OR SERVICES FROM OR REGARDING THE WEBSITE, CONTENT, OR YOUR PURCHASES FROM US. WE DO NOT WARRANT THAT THE WEBSITE, PRODUCTS OR SERVICES WILL BE COMPATIBLE WITH ANY HARDWARE OR SOFTWARE SYSTEMS OR THAT THE WEBSITE OR ANY SERVICES WILL BE UNINTERRUPTED OR ERROR FREE. </p>
        <p>WE ARE NOT RESPONSIBLE OR LIABLE FOR MAINTAINING ANY CONSUMER DATA OR FOR THE DELETION, CORRUPTION, DESTRUCTION, DAMAGE, LOSS OR FAILURE OF ANY CONSUMER DATA OR FOR ANY THIRD-PARTY ACCESS TO ANY CONSUMER DATA.  </p>
        <p>WE MAKE NO WARRANTY OR REPRESENTATION AS TO THE LEVEL OF SUCCESS, IF ANY, INDIVIDUALS MAY ACHIEVE BY USING ANY OF OUR PRODUCTS OR SERVICES. INDIVIDUAL RESULTS MAY VARY AND DEPEND ON MANY FACTORS INCLUDING AN INDIVIDUAL’S SPECIFIC FINANCIAL SITUATION, EFFORTS AND ACTIONS. YOU SHOULD SEEK THE ADVICE OF 5 QUALIFIED PROFESSIONALS SUCH AS AN ACCOUNTANT, ATTORNEY AND/OR PROFESSIONAL ADVISOR FOR SPECIFIC ADVICE FOR YOUR BUSINESS. </p>
        <p>FURTHER, WE AND OUR LICENSORS MAKE NO REPRESENTATION OR WARRANTIES THAT THE CONTENT OR THE SERVICES OR THE MATERIALS AND TECHNOLOGY AVAILABLE ON OR THROUGH THE WEBSITE ARE APPROPRIATE OR AVAILABLE FOR USE IN ALL GEOGRAPHIC LOCATIONS. IF YOU USE THE WEBSITE, THE SERVICES OR ANY MATERIALS OR TECHNOLOGY AVAILABLE ON OR THROUGH THE WEBSITE OUTSIDE ESTONIA, YOU ARE SOLELY RESPONSIBLE FOR COMPLIANCE WITH ALL APPLICABLE LAWS, INCLUDING WITHOUT LIMITATION, EXPORT AND IMPORT REGULATIONS OF OTHER COUNTRIES. NEITHER WE NOR ANY THIRD-PARTY PROVIDERS, PARTNERS OR AFFILIATES WARRANT THAT SITE, ITS SERVERS OR ANY E-MAIL SENT FROM THE WEBSITE OR ANY THIRD-PARTY PROVIDERS, PARTNERS OR AFFILIATES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.  </p>
        <p>Use of Services</p>
        <p>By way of example, and not as a limitation, you agree that when using our Content, Services or any other portion of the Website, you will not:</p>
        <p>(i) Modify, delete, decompile, disassemble or reverse engineer the Website, Content or Services in any way whatsoever;<br />
        (ii) Defame, abuse, harass, stalk, threaten, or otherwise violate the legal rights (such as rights of privacy and publicity) of others; <br />
        (iii) Use the Services except as expressly provided in these Terms of Use or publish, transmit, copy, reproduce, e-mail, post, upload, distribute, or disseminate (or use the Website or Content to do any of the foregoing with respect to) any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful topic, name, material, or information;<br />
        (iv) Upload ﬁles that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents;<br />
        (v) Upload ﬁles that contain viruses, corrupted ﬁles, or any other similar software or program that may damage the operation of another’s computer;<br />
        (vi) Advertise or offer to sell or buy any goods or services for any business purpose, unless such Service speciﬁcally allows such messages;<br />
        (vii) Conduct or forward surveys, contests, pyramid schemes, chain letters, junk mail, spam, unsolicited e-mail, or any advertising, promotional, or unauthorized communication;<br />
        (viii) Download any ﬁle posted by another user of a Service that you know, or reasonably should know, cannot be legally distributed in such manner;<br />
        (ix) Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software, or other material contained in a ﬁle that is uploaded;<br />
        (x) Restrict or inhibit any other user from using and enjoying the Services or any other portion of the Website or Content;<br />
        (xi) Violate any code of conduct or other guidelines that may be applicable for any particular Service or any other portion of the Website or Content;<br />
        (xii) Harvest or otherwise collect information about others, including, but not limited to, e-mail addresses, without their prior, express, and written consent;<br />
        (xiii) Violate any applicable laws, rules or regulations;<br />
        (xiv) Use the Services if you are located in a country embargoed by Estonia Specially Designated Nationals; or <br />
        (xv) Share your password, let anyone else access your account, or do anything else that might jeopardize the security of your account.
        </p>
        <p>We have no obligation to monitor the Services, the Website or Content. However, we reserve the right to review materials posted to a Service and to remove any materials in our sole discretion. We assume no liability relating to our monitoring acts or omissions.</p>
        <p>We reserve the right at all times to disclose any information as necessary to satisfy any applicable law, rule, regulation, legal process, or governmental request, or to edit, refuse to post, or to remove any information or materials, in whole or in part, in our sole discretion.</p>
        <p>Materials uploaded to a Service may be subject to posted limitations on usage, reproduction, and/or dissemination. You are responsible for adhering to such limitations if you download the materials.
        </p>
        <p>Information Provided to Us</p>
        <p>Subject to the Privacy Policy, any and all information, data, sound, photographs, videos, and works of authorship that you provide to us, including all comments and suggestions (collectively “Visitor Generated Content”), you grant us a non-exclusive, transferable, assignable, sublicensable, perpetual, irrevocable, worldwide, royalty-free, and fully paid-up license to use, possess, copy, distribute, sell, sublicense, disclose, display publicly, perform, modify, make, have made, import, export, and prepare derivative works of such Visitor Generated Content through multiple tiers of distribution in any and all media now known or hereafter invented.</p>
        <p>No compensation will be paid with respect to the use of your Visitor Generated Content, as provided herein. We are under no obligation to post or use any Visitor Generated Content you may provide and may remove any Visitor Generated Content at any time in our sole discretion.</p>
        <p>By posting, uploading, inputting, providing, or submitting your Visitor Generated Content, you represent and warrant that you own or otherwise control all of the rights to your Visitor Generated Content as described in this section including, but not limited to, all the rights necessary for you to provide, post, upload, input, or submit the Visitor Generated Content.</p>
        <p>You are legally responsible for all Visitor Generated Content uploaded, posted, or stored through your use of the Services.</p>
        <p>Our Services may include bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other messaging facilities designed to enable you to upload or distribute information, materials and other content, or to communicate with the public at-large or with a group. You are solely responsible for all information, images, graphics, data, text, ﬁles, links, software, messages, communications, and other materials (the “End User Content”) that you (or someone using your account) publicly or privately publish, post, distribute, display, disseminate, or otherwise transmit via the Website. We do not control or necessarily screen or monitor the End User Content posted on the Website and, as such, we do not guarantee the accuracy, integrity, or quality of such End User Content. We reserve the right, in our sole and absolute discretion, to edit, delete, or record any End User Content appearing on the Website. You understand that entering or using the Website may expose you to End User Content that is offensive, indecent, or objectionable to you. You agree to use the Services only to post, send, and receive messages and material that are proper and related to the particular Service. You grant to us a limited non-exclusive, transferable, assignable, sublicenseable, irrevocable, worldwide, royalty-free, and fully paid-up license to use, possess, copy, distribute, sell, sublicense, disclose, display publicly, perform, modify, make, have made, import, export, and prepare derivative works of the End User Content for purposes of providing to you the Services for which the End User Content was provided.
        </p>
        <p>Special Notice Regarding Copyright Infringement</p>
        <p>Limitation of Liability</p>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE AND OUR AFFILIATED PARTIES SHALL HAVE NO LIABILITY WHATSOEVER FOR YOUR USE OF ANY CONTENT OR OTHER INFORMATION OR SERVICE RELATED TO THE WEBSITE AND SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS, OR LITIGATION), (I) ARISING FROM ANY DECISION MADE OR ACTION TAKEN BY YOU IN RELIANCE UPON THE CONTENT OR OUR PRODUCTS OR SERVICES, (II) ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE WEBSITE OR CONTENT, OR WITH THE DELAY OR INABILITY TO USE THE WEBSITE, CONTENT, OR RELATED SERVICES, OR FROM THE USE OR MISUSE OF ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES, RELATED GRAPHICS, AND CONTENT OBTAINED THROUGH THE WEBSITE, (III) ANY INCORRECT OR MISSING INFORMATION OR DATA, OR (IV) OTHERWISE ARISING OUT OR RESULTING FROM LOSS OF YOUR DATA OR INFORMATION, WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE), OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.<br /><br />
        WE ARE NOT RESPONSIBLE FOR INTERRUPTED, INACCESSIBLE OR UNAVAILABLE NETWORKS, SERVERS, SATELLITES, INTERNET SERVICE PROVIDERS, WEBSITES, OR OTHER CONNECTIONS, OR FOR MISCOMMUNICATIONS, FAILED, JUMBLED, SCRAMBLED, DELAYED, OR MISDIRECTED COMPUTER, TELEPHONE OR CABLE TRANSMISSIONS, OR FOR ANY TECHNICAL MALFUNCTIONS, FAILURES OR DIFFICULTIES. <br /><br /><br />
        THE ABOVE LIMITATIONS AND EXCLUSIONS SHALL APPLY TO YOU TO THE FULLEST EXTENT THAT APPLICABLE LAW PERMITS, IN ALL ACTIONS OF ANY KIND, WHETHER BASED ON CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR ANY OTHER LEGAL OR EQUITABLE THEORY. ANY CLAUSE DECLARED INVALID SHALL BE DEEMED SEVERABLE AND NOT AFFECT THE VALIDITY OR ENFORCEABILITY OF THE REMAINDER OF THESE TERMS OF USE.
        </p>
        <p>Links</p>
        <p>The Website may, from time to time, contain links to or reference third party websites, resources and advertisers (collectively, “Third Party Sites”). Your linking to such Third-Party Sites is at your own risk. We are not responsible for the accuracy or reliability of any content, data, opinions, advice, statements, or other information made on the Third-Party Sites. We do not investigate, monitor, or check such Third-Party Sites for accuracy or completeness. We are not responsible for the availability of these Third-Party Sites, nor are we responsible for the aesthetics, appeal, suitability to taste or subjective quality of informational content, advertising, products or other materials made available on or through such Third-Party Sites. We are providing these links to you only as a convenience and may discontinue providing such links at any time in our sole discretion without notice to you. No endorsement of any third-party content, information, data, opinions, advice, statements, goods, services or products is expressed or implied by any information, material or content of any Third-Party Site contained in, referred to, included on, or linked from or to, the Website. If you decide to leave the Website and access these Third-Party Sites, you do so at your own risk. Under no circumstances shall we or any afﬁliated providers be held responsible or liable, directly or indirectly, for any loss, injury, or damage caused or alleged to have been caused to you in connection with the use of, or reliance on, any content, information, data, opinions, advice, statements, goods, services, or products available on such Third Party Sites. You should direct any concerns to the respective Third-Party Site’s administrator or webmaster. Any links to Third Party Sites do not imply that we are legally authorized to use any trademark, trade name, logo or copyright symbol displayed in or accessible through such links, or that any linked Third Party Site is authorized to use any trademark, trade name, logo or copyright symbol of ours.</p>
        <p>Linking to Our Corporate Site</p>
        <p>If you are an Afﬁliate of Elysium, you are granted a limited, non-exclusive right to create a hypertext link to the Website from the self-replicating website we provide to you, provided such link is in compliance with these Terms of Use, the Elysium Agreement and our Policies and Procedures. You cannot create an impression that any subdomain on the Website is part of your website. This limited right may be revoked at any time.</p>
        <p>Modiﬁcation</p>
        <p>We reserve the right, in our sole discretion, to change, modify, add, or remove portions of these Terms of Use at any time. You should read these Terms of Use periodically for changes. If you use the Website after we post changes to these Terms of Use, you will be deemed to have accepted the changed Terms of Use.</p>
        <p>Governing Law</p>
        <p>These Terms of Use shall be governed by, and construed and enforced in accordance with, the laws of the of Estonia, without regard to conﬂicts of law principles. Any cause of action by you with respect to the Website must be instituted within two years after the cause of action arose or be forever waived and barred. Any legal action concerning these Terms of Use shall be brought before a court of competent jurisdiction in Estonia. The parties hereby consent to such jurisdiction and venue.</p>
        <p>Relief Available for Violation</p>
        <p>In the event of an actual or threatened violation of these Terms of Use, these Terms of Use may be enforced by injunctive relief or speciﬁc performance without proof of actual damages but upon proof of all other requirements for the grant of such relief, in addition to any and all other available remedies.</p>
        <p>Miscellaneous</p>
        <p>The provisions of these Terms of Use are severable, and in the event any provision of these Terms of Use is determined to be invalid or unenforceable, such invalidity or unenforceability shall not in any way affect the validity or enforceability of the remaining provisions. Our waiver of a breach of any provision of these Terms of Use by you shall not operate or be construed as a waiver by us of any subsequent breach by you.</p>
        <p>This Section, and the provisions of these Terms of Use addressing disclaimers of representations and warranties, indemnity obligations, intellectual property and governing law, shall survive the termination of these Terms of Use.</p>
        <p>These Terms of Use do not limit any rights or remedies that we or our suppliers, licensors, or other similar entities, may have under trade secret, copyright, patent, trademark or other laws.</p>
        <p>These Terms of Use, and our Privacy Policy, and any end user click-through agreements contained on the Website and, if you are an Afﬁliate of Elysium, your Elysium  Agreement and the Policies and Procedures, constitute the entire agreement between us with respect to your use of the Website, and supersede all previous written or oral agreements. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for convenience only and shall not be given any legal import.</p>
        <p>A printed version of these Terms of Use and of any notice given in electronic form shall be admissible in arbitration or any judicial or administrative proceedings based upon, or relating to, these Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish of the parties that these Terms of Use and all related documents be drawn up in English as spoken in Estonia.</p>
        <p>BY USING THE WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE, UNDERSTAND THEM AND AGREE TO BE BOUND BY ALL THE TERMS AND CONDITIONS HEREIN, AS AMENDED FROM TIME TO TIME</p>


    </div>
</div>
